spring.application.name=backend-cartes

spring.datasource.url=jdbc:hsqldb:hsql://localhost/xdb
spring.datasource.driverClassName=org.hsqldb.jdbc.JDBCDriver
spring.datasource.username=sa
spring.datasource.password=